### ISSUE TITLE
Alphabetical sorting of JSON in pretty printed format

### ISSUE THREAD

**Issue by hydroxy** [dicksonlaw583/JsonStruct#6]
I am writing JSON data to file using the jsons_save_formatted function. The program that reads the file expects the JSON fields to be in alphabetical order, however this is not what I see. It seems capital letters come first rather than using non-case sensitive sorting.

For example below is an output JSON segment, notice how the inheritItemSettings comes before inheritedItemId.

```
"inheritCode": false, 
**"inheritItemSettings": false,** 
**"inheritedItemId": null,** 
"isDnd": false, 
"name": "instance1", 
```

Is there a way to use a non-case sensitive sort with the jsons_save_formatted function?

**Comment by dicksonlaw583** [comment]
For now, you can edit the `array_sort` line in `JsonStruct_internal` (currently [line 485](https://github.com/dicksonlaw583/JsonStruct/blob/main/scripts/JsonStruct_Internal/JsonStruct_Internal.gml#L485)) to use a case-insensitive sort. I may consider adding a configuration for changing the second argument to `array_sort` in a future release.

**Comment by hydroxy** [comment]
Thanks, that's exactly what I was looking for :)

JsonStruct is a nice addition to GameMaker by the way. These functions should be natively included.
